name: "Test CI"

on: [push, pull_request]

jobs:
  tests:
    runs-on: testing
    steps:
      - name: Clone the repository
        uses: actions/checkout@v6

      - name: Check for flake configurations
        run: nix flake check --all-systems --show-trace

      - name: Run lint
        run: nix develop --command bash -c "cargo clippy --verbose"

      - name: Run format check
        run: nix develop --command bash -c "cargo fmt --all -- --check"

      - name: Build nix package
        run: nix build . --show-trace
